// Code generated by protoc-gen-go.
// source: app.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	app.proto
	auth.proto
	deployment.proto

It has these top-level messages:
	App
	ConfigRequest
	ConfigResponse
	AppCreateResponse
	User
	AuthResponse
	DeploymentRequest
	DeploymentJob
	DeploymentResponse
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// App represents an app
type App struct {
	Name   string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Owner  string            `protobuf:"bytes,2,opt,name=owner" json:"owner,omitempty"`
	Config map[string]string `protobuf:"bytes,3,rep,name=config" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Repo   string            `protobuf:"bytes,4,opt,name=repo" json:"repo,omitempty"`
}

func (m *App) Reset()                    { *m = App{} }
func (m *App) String() string            { return proto.CompactTextString(m) }
func (*App) ProtoMessage()               {}
func (*App) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *App) GetConfig() map[string]string {
	if m != nil {
		return m.Config
	}
	return nil
}

// ConfigRequest represents a config request
type ConfigRequest struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Key   string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
}

func (m *ConfigRequest) Reset()                    { *m = ConfigRequest{} }
func (m *ConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*ConfigRequest) ProtoMessage()               {}
func (*ConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// ConfigResponse represents a config response
type ConfigResponse struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *ConfigResponse) Reset()                    { *m = ConfigResponse{} }
func (m *ConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*ConfigResponse) ProtoMessage()               {}
func (*ConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// AppCreateResponse represents an app creation response
type AppCreateResponse struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *AppCreateResponse) Reset()                    { *m = AppCreateResponse{} }
func (m *AppCreateResponse) String() string            { return proto.CompactTextString(m) }
func (*AppCreateResponse) ProtoMessage()               {}
func (*AppCreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*App)(nil), "api.App")
	proto.RegisterType((*ConfigRequest)(nil), "api.ConfigRequest")
	proto.RegisterType((*ConfigResponse)(nil), "api.ConfigResponse")
	proto.RegisterType((*AppCreateResponse)(nil), "api.AppCreateResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion1

// Client API for AppService service

type AppServiceClient interface {
	CreateApp(ctx context.Context, in *App, opts ...grpc.CallOption) (*AppCreateResponse, error)
	GetApp(ctx context.Context, in *App, opts ...grpc.CallOption) (*App, error)
	GetAppConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error)
	SetAppConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error)
}

type appServiceClient struct {
	cc *grpc.ClientConn
}

func NewAppServiceClient(cc *grpc.ClientConn) AppServiceClient {
	return &appServiceClient{cc}
}

func (c *appServiceClient) CreateApp(ctx context.Context, in *App, opts ...grpc.CallOption) (*AppCreateResponse, error) {
	out := new(AppCreateResponse)
	err := grpc.Invoke(ctx, "/api.AppService/CreateApp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) GetApp(ctx context.Context, in *App, opts ...grpc.CallOption) (*App, error) {
	out := new(App)
	err := grpc.Invoke(ctx, "/api.AppService/GetApp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) GetAppConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error) {
	out := new(ConfigResponse)
	err := grpc.Invoke(ctx, "/api.AppService/GetAppConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) SetAppConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error) {
	out := new(ConfigResponse)
	err := grpc.Invoke(ctx, "/api.AppService/SetAppConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AppService service

type AppServiceServer interface {
	CreateApp(context.Context, *App) (*AppCreateResponse, error)
	GetApp(context.Context, *App) (*App, error)
	GetAppConfig(context.Context, *ConfigRequest) (*ConfigResponse, error)
	SetAppConfig(context.Context, *ConfigRequest) (*ConfigResponse, error)
}

func RegisterAppServiceServer(s *grpc.Server, srv AppServiceServer) {
	s.RegisterService(&_AppService_serviceDesc, srv)
}

func _AppService_CreateApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(App)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(AppServiceServer).CreateApp(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _AppService_GetApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(App)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(AppServiceServer).GetApp(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _AppService_GetAppConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(AppServiceServer).GetAppConfig(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _AppService_SetAppConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(AppServiceServer).SetAppConfig(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _AppService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.AppService",
	HandlerType: (*AppServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateApp",
			Handler:    _AppService_CreateApp_Handler,
		},
		{
			MethodName: "GetApp",
			Handler:    _AppService_GetApp_Handler,
		},
		{
			MethodName: "GetAppConfig",
			Handler:    _AppService_GetAppConfig_Handler,
		},
		{
			MethodName: "SetAppConfig",
			Handler:    _AppService_SetAppConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x92, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0xdf, 0x64, 0xfb, 0x06, 0x33, 0x55, 0xd1, 0xb5, 0x48, 0xc8, 0x41, 0x4a, 0x2e, 0xf6,
	0x20, 0x11, 0xea, 0xa5, 0xf5, 0x26, 0x41, 0x3c, 0x78, 0x4b, 0x3f, 0xc1, 0x5a, 0x46, 0x09, 0xea,
	0xee, 0xba, 0xd9, 0x56, 0xfa, 0x9d, 0xfc, 0x36, 0x7e, 0x21, 0xf7, 0x4f, 0x12, 0x1a, 0xc8, 0x41,
	0xbc, 0x3d, 0x3b, 0x33, 0xcf, 0x6f, 0x26, 0x0f, 0x81, 0x98, 0x49, 0x99, 0x4b, 0x25, 0xb4, 0xa0,
	0x84, 0xc9, 0x2a, 0xfb, 0x0a, 0x80, 0xdc, 0x49, 0x49, 0x29, 0x8c, 0x38, 0x7b, 0xc7, 0x24, 0x98,
	0x06, 0xb3, 0xb8, 0x74, 0x9a, 0x4e, 0xe0, 0xbf, 0xf8, 0xe4, 0xa8, 0x92, 0xd0, 0x15, 0xfd, 0x83,
	0x5e, 0x41, 0xb4, 0x16, 0xfc, 0xb9, 0x7a, 0x49, 0xc8, 0x94, 0xcc, 0xc6, 0xf3, 0x49, 0x6e, 0x38,
	0xb9, 0x61, 0xe4, 0x85, 0x2b, 0xdf, 0x73, 0xad, 0x76, 0x65, 0x33, 0x63, 0xb9, 0x0a, 0xa5, 0x48,
	0x46, 0x9e, 0x6b, 0x75, 0xba, 0x84, 0xf1, 0xde, 0x28, 0x3d, 0x01, 0xf2, 0x8a, 0xbb, 0x66, 0xb3,
	0x95, 0x76, 0xf1, 0x96, 0xbd, 0x6d, 0xb0, 0x5d, 0xec, 0x1e, 0xb7, 0xe1, 0x22, 0xc8, 0x1e, 0xe1,
	0xc8, 0x5b, 0x4b, 0xfc, 0xd8, 0x60, 0xad, 0x07, 0xef, 0x6e, 0x80, 0xe1, 0x00, 0x90, 0xec, 0x01,
	0xb3, 0x05, 0x1c, 0xb7, 0xb0, 0x5a, 0x0a, 0x5e, 0xe3, 0x6f, 0x4f, 0xc9, 0x2e, 0xe1, 0xd4, 0x7c,
	0x70, 0xa1, 0x90, 0x69, 0xec, 0xcc, 0x03, 0xa7, 0xcc, 0xbf, 0x03, 0x00, 0x33, 0xb9, 0x42, 0xb5,
	0xad, 0xd6, 0x48, 0xaf, 0x21, 0xf6, 0x26, 0x1b, 0xf9, 0x41, 0x1b, 0x5c, 0x7a, 0xde, 0xaa, 0x3e,
	0x31, 0xfb, 0x47, 0x2f, 0x20, 0x7a, 0x40, 0xdd, 0x9f, 0xee, 0x94, 0xe9, 0x2f, 0xe1, 0xd0, 0xf7,
	0x8b, 0x26, 0x6e, 0xd7, 0xeb, 0x45, 0x94, 0x9e, 0xf5, 0x6a, 0x1d, 0xda, 0x58, 0x57, 0x7f, 0xb3,
	0x3e, 0x45, 0xee, 0x07, 0xba, 0xf9, 0x09, 0x00, 0x00, 0xff, 0xff, 0xc1, 0x76, 0xc7, 0x55, 0x4d,
	0x02, 0x00, 0x00,
}
